---
title: "Wins Models"
author: "DJ Fugate"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(caret)
library(stats)
library(car)
library(randomForest)
library(rpart)
```

# Load in Team CSV

```{r}
teams <- read.csv("Teams.csv")

set.seed(546)
```


# Teams Data

```{r}
# Filter data from 2000 on, adding Run_Diff
teams2 <- teams %>% 
  filter(yearID > 1980) %>% 
  mutate(Run_Diff = R - RA,
         AVG = H/AB,
         SLUG = ((H-X2B-X3B-HR)+(2*X2B)+(3*X3B)+(4*HR))/AB) %>% 
  select(-c(HBP,SF))

# Copy of teams2 
teams2.copy <- teams2

# Get rid of high level/unneeded rows
teams2 <- teams2[,-c(1:7,10:20,25:26,31,36,39:40,44:46)]

# Get train and test data
train_rows <- sample(1:nrow(teams2), .8 * nrow(teams2))
train_data <- teams2[train_rows,]
test_data <- teams2[-train_rows,]

# Team Wins Model with all of variables
Wins_Model <- lm(W~.,data = train_data)
summary(Wins_Model)

# Team Wins Model 1 statistics
predicted_values <- predict(Wins_Model, test_data)
mse <- mean((test_data$W - predicted_values)^2); mse # Mean Square Error
rmse <- sqrt(mse); rmse   # RMSE
r_squared <- 1 - sum((test_data$W - predicted_values)^2) / sum((test_data$W - mean(test_data$W))^2)
r_squared # on test data

# Team Wins Model using significant variables from first model
Wins_Model2 <- lm(W~Ghome+BB+ERA+CG+SHO+SV+HA+SOA+FP+attendance+Run_Diff+SLUG, data=train_data)
summary(Wins_Model2)

# Teams Wins Model 2 statistics
predicted_values <- predict(Wins_Model2, test_data)
mse <- mean((test_data$W - predicted_values)^2); mse # Mean Square Error
rmse <- sqrt(mse); rmse   # RMSE
r_squared <- 1 - sum((test_data$W - predicted_values)^2) / sum((test_data$W - mean(test_data$W))^2)
r_squared #on test data
```

# Seeing top 5 misses of Model

```{r}
diff<-teams2$W[-train_rows]-predicted_values

error<-sqrt(sum(diff**2)/(nrow(test_data)))

order(diff,decreasing=TRUE)

max(diff)

test_data$diff<- diff

test_data$predictedW<- predicted_values

extracted_rows <- teams2.copy[rownames(test_data), ]
order(abs(diff),decreasing=TRUE) #129,117,51,92,67

#2003 Giants (Actual:100, Predicted:91)
extracted_rows[129,]
test_data[129,]

#2002 Red Sox (Actual:93, Predicted:101)
extracted_rows[117,]
test_data[117,]

#1989 Astros (Actual:86, Predicted:77)
extracted_rows[51,]
test_data[51,]

#1997 Giants (Actual:90, Predicted:81)
extracted_rows[92,]
test_data[92,]

#1993 Mets (Actual:59, Predicted:66)
extracted_rows[67,]
test_data[67,]
```

```{r}
test_data$yearID <- extracted_rows$yearID


ggplot(test_data, aes(x=yearID)) +
  geom_smooth(aes(y=W, color="Observed"), se=FALSE) +
  geom_smooth(aes(y=predictedW, color="Predicted"), se=FALSE) +
  labs(x="Year", y="Wins", title="Predicted W vs Observed W",
       caption = '') +
  scale_color_manual(values=c("Observed"="red", "Predicted"="black")) +
  theme(legend.title=element_blank()) # Optional: remove the legend title if desired
```

# Final Paper All Models
## Linear
```{r}
ctrl <- trainControl(
  method = "repeatedcv",
  number = 5,
  repeats = 3,  # Repeat the cross-validation 3 times
  summaryFunction = defaultSummary
)

# Team Wins Model with all of variables
Wins_Model_After <- train(W~.,
                    data = train_data,
                    method = "lm",
                    trControl = ctrl)

Wins_Model_After$results
WMA_predicted_values <- predict(Wins_Model_After, test_data)
WMA_mse <- mean((test_data$W - WMA_predicted_values)^2); WMA_mse # Mean Square Error
WMA_rmse <- sqrt(WMA_mse); WMA_rmse

# Team Wins Model using significant variables from first model
Wins_Model_After2 <- train(W~Ghome+BB+ERA+CG+SHO+SV+HA+SOA+FP+attendance+Run_Diff+SLUG,
                     data=train_data,
                     method = "lm",
                     trControl = ctrl)
summary(Wins_Model_After2)
Wins_Model_After2$results

WMA2_predicted_values <- predict(Wins_Model_After2, test_data)
WMA2_mse <- mean((test_data$W - WMA2_predicted_values)^2); WMA2_mse # Mean Square Error
WMA2_rmse <- sqrt(WMA2_mse); WMA2_rmse
```

## Random Forest
```{r}
rf_model <- train(
  W ~Ghome+BB+ERA+CG+SHO+SV+HA+SOA+FP+attendance+Run_Diff+SLUG,
  data = train_data,
  method = "rf",
  trControl = ctrl,
  tuneGrid = expand.grid(mtry = c(2,5,8,11))
)

rf_model$results

rf_predicted_values <- predict(rf_model, test_data)
mse <- mean((test_data$W - rf_predicted_values)^2); mse # Mean Square Error
rmse <- sqrt(mse); rmse   # RMSE
r_squared <- 1 - sum((test_data$W - rf_predicted_values)^2) / sum((test_data$W - mean(test_data$W))^2)
r_squared
```


